version: "3"

services:
  api:
    image: thats-a-nice-argument-unfortunately-dot-com-api:${IMAGE_VERSION}
    container_name: "web_api-thats-a-nice-argument-unfortunately-dot-com"
    environment:
      - IPINFO_API_KEY=${IPINFO_API_KEY}
      - PROXYCHECK_API_KEY=${PROXYCHECK_API_KEY}
    ports:
      - 6015:8000
